"""add discovery tables and post image_source

Revision ID: e25708ce582b
Revises: 4df2b50aaeda
Create Date: 2026-08-06 23:00:15.099895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25708ce582b'
down_revision: Union[str, Sequence[str], None] = '4df2b50aaeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_headline', sa.String(length=500), nullable=True),
    sa.Column('author_profile_url', sa.String(length=500), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('metrics_source', sa.String(length=20), nullable=False),
    sa.Column('serp_rank', sa.Integer(), nullable=True),
    sa.Column('query_overlap', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('layout_skeleton', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_as_reference', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_url')
    )
    op.create_index(op.f('ix_discovered_posts_keyword'), 'discovered_posts', ['keyword'], unique=False)
    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parse_failures', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('image_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_source')
    op.drop_table('discovery_jobs')
    op.drop_index(op.f('ix_discovered_posts_keyword'), table_name='discovered_posts')
    op.drop_table('discovered_posts')
    # ### end Alembic commands ###
